"""Pruned XGBoost strategy using SHAP-selected features.

Reduces overfitting by using only the top N features identified
via SHAP TreeExplainer, instead of the full 131 features.
"""

from typing import Dict, Optional

from tradingagents.baselines.ml_strategy import MLStrategy
from tradingagents.models.ml_trainer import load_selected_features


class MLStrategyPruned(MLStrategy):
    """MLStrategy with SHAP-pruned feature set.

    Identical behavior to MLStrategy, but only uses features listed
    in selected_features.json (generated by scripts/shap_analysis.py).
    """

    def __init__(
        self,
        model_type: str = "xgboost",
        include_sentiment: bool = True,
        config: Dict = None,
        selected_features_path: Optional[str] = None,
    ):
        features = load_selected_features(selected_features_path)
        if features is None:
            raise FileNotFoundError(
                "No selected_features.json found. "
                "Run: python -m scripts.shap_analysis --top-n 20"
            )
        super().__init__(
            model_type=model_type,
            include_sentiment=include_sentiment,
            config=config,
            selected_features=features,
        )
        self._n_selected = len(features)

    def analyze(self, ticker: str, trade_date: str, **kwargs) -> Dict:
        result = super().analyze(ticker, trade_date, **kwargs)
        # Override strategy name to distinguish from unpruned
        result["strategy"] = f"ml_{self.model_type}_pruned"
        # Annotate raw response with pruning info
        result["raw_response"] = result["raw_response"].replace(
            f"ML Model: {self.model_type}",
            f"ML Model: {self.model_type} (pruned, {self._n_selected} features)",
        )
        return result
